name: Test GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test step
        run: |
          echo "✅ GitHub Actions 正常工作！"
          echo "当前时间: $(date)"
          echo "GitHub 版本: ${{ github.server_url }}"
          echo "仓库: ${{ github.repository }}"
          echo "分支: ${{ github.ref_name }}"
          echo "提交: ${{ github.sha }}"

      - name: Check environment
        run: |
          echo "系统信息:"
          uname -a
          echo "内存使用:"
          free -h
          echo "磁盘使用:"
          df -h
